from __future__ import annotations

import logging
from typing import Any, Dict, List

from langchain_core.messages import HumanMessage, SystemMessage

from uppgrad_agentic.common.llm import get_llm
from uppgrad_agentic.workflows.auto_apply.schemas import AssetMap, AssetMappingOutput
from uppgrad_agentic.workflows.auto_apply.state import AutoApplyState

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Stub profile accessor — shared definition lives in eligibility_and_readiness.
# Importing it directly keeps a single source of truth for the stub.
# ---------------------------------------------------------------------------
from uppgrad_agentic.workflows.auto_apply.nodes.eligibility_and_readiness import _get_stub_profile

# ---------------------------------------------------------------------------
# Document types the system can write/generate vs. ones the user must supply
# ---------------------------------------------------------------------------

# Can be written from profile/CV data
_GENERATABLE: set[str] = {
    "CV",
    "Cover Letter",
    "Motivation Letter",
    "SOP",
    "Personal Statement",
    "Research Proposal",
    "Writing Sample",
    "References",
}

# Must be provided by the user — cannot be authored by the system
_USER_SUPPLIED: set[str] = {
    "Transcript",
    "English Proficiency Test",
    "Portfolio",
    "Certificate",
    "Passport",
    "Birth Certificate",
}


SYSTEM = """You are an application assistant mapping a job-seeker's documents to opportunity requirements.

For each required document, decide:
- source_document: which existing user document to use as the base (e.g. "CV", "profile", or "" if none)
- tailoring_depth:
    "none"     — requirement cannot be generated (e.g. transcripts, test scores, portfolios); user must supply it
    "light"    — user already has this document; it only needs minor adjustments for this opportunity
    "deep"     — user has a related document but it needs substantial reworking for this context
    "generate" — no suitable source document exists; must be created from scratch using profile data
- available: true only if the user already has the EXACT document type on file
- notes: one sentence explaining the decision or flagging something the user should know

Rules:
- If a document type requires a test/grade/transcript that cannot be written, use "none".
- If user has CV and needs Cover Letter, use source_document="CV" and tailoring_depth="generate".
- If user has CV and needs SOP/Personal Statement, use source_document="CV" and tailoring_depth="generate".
- If user has the exact document, default to "light" unless the opportunity is very specialised (then "deep").
- For References, use source_document="profile" and tailoring_depth="generate" since they come from contacts.

Return JSON only."""


# ---------------------------------------------------------------------------
# Heuristic mapping (LLM-free fallback)
# ---------------------------------------------------------------------------

def _heuristic_map(
    doc_type: str,
    req_type: str,
    uploaded: Dict[str, bool],
) -> AssetMap:
    """Decide source_document, tailoring_depth, available, and notes without LLM."""

    # Non-document requirements carry no writable deliverable
    if req_type != "document":
        return AssetMap(
            requirement_type=doc_type,
            source_document="",
            tailoring_depth="none",
            available=False,
            notes=f"{doc_type} is not a writable document; the user must supply it directly.",
        )

    has_doc = bool(uploaded.get(doc_type))
    has_cv = bool(uploaded.get("CV"))

    # Exact document on file
    if has_doc:
        return AssetMap(
            requirement_type=doc_type,
            source_document=doc_type,
            tailoring_depth="light",
            available=True,
            notes=f"Existing {doc_type} on file; will be lightly tailored to this opportunity.",
        )

    # User must supply — cannot generate
    if doc_type in _USER_SUPPLIED:
        return AssetMap(
            requirement_type=doc_type,
            source_document="",
            tailoring_depth="none",
            available=False,
            notes=f"{doc_type} must be provided by the user; it cannot be generated by the system.",
        )

    # References — drawn from profile contacts
    if "reference" in doc_type.lower() or "recommendation" in doc_type.lower():
        return AssetMap(
            requirement_type=doc_type,
            source_document="profile",
            tailoring_depth="generate",
            available=False,
            notes="References will be compiled from contacts stored in your profile.",
        )

    # Generatable documents: Cover Letter, SOP, Personal Statement, Research Proposal, etc.
    if doc_type in _GENERATABLE:
        if has_cv and doc_type != "CV":
            return AssetMap(
                requirement_type=doc_type,
                source_document="CV",
                tailoring_depth="generate",
                available=False,
                notes=f"No {doc_type} on file; will be generated from your CV and profile data.",
            )
        return AssetMap(
            requirement_type=doc_type,
            source_document="profile",
            tailoring_depth="generate",
            available=False,
            notes=f"No {doc_type} on file; will be generated from profile data only.",
        )

    # Unknown document type — best-effort deep adaptation from CV
    if has_cv:
        return AssetMap(
            requirement_type=doc_type,
            source_document="CV",
            tailoring_depth="deep",
            available=False,
            notes=f"No {doc_type} on file; CV will be deeply adapted to approximate this document.",
        )
    return AssetMap(
        requirement_type=doc_type,
        source_document="profile",
        tailoring_depth="generate",
        available=False,
        notes=f"No suitable source document for {doc_type}; will generate from profile data.",
    )


def _heuristic_asset_mapping(
    normalized_requirements: List[Dict[str, Any]],
    uploaded: Dict[str, bool],
) -> List[AssetMap]:
    return [
        _heuristic_map(
            doc_type=req.get("document_type", ""),
            req_type=req.get("requirement_type", "document"),
            uploaded=uploaded,
        )
        for req in normalized_requirements
    ]


# ---------------------------------------------------------------------------
# LLM mapping
# ---------------------------------------------------------------------------

def _build_llm_prompt(
    opportunity_data: Dict[str, Any],
    opportunity_type: str,
    normalized_requirements: List[Dict[str, Any]],
    profile: Dict[str, Any],
) -> str:
    title = opportunity_data.get("title", "Unknown")
    company = (
        opportunity_data.get("company")
        or opportunity_data.get("university")
        or opportunity_data.get("provider_name")
        or "Unknown"
    )
    uploaded = profile.get("uploaded_documents") or {}
    uploaded_list = [k for k, v in uploaded.items() if v]
    reqs_list = [
        f"- {r.get('document_type')} (requirement_type={r.get('requirement_type')}, assumed={r.get('is_assumed')})"
        for r in normalized_requirements
    ]

    return (
        f"Opportunity: {title} at {company} (type: {opportunity_type})\n\n"
        f"User's uploaded documents: {', '.join(uploaded_list) if uploaded_list else 'none'}\n\n"
        f"Required documents:\n" + "\n".join(reqs_list) + "\n\n"
        "Produce one AssetMap entry per required document."
    )


def _llm_asset_mapping(
    opportunity_data: Dict[str, Any],
    opportunity_type: str,
    normalized_requirements: List[Dict[str, Any]],
    profile: Dict[str, Any],
    llm,
) -> List[AssetMap] | None:
    structured = llm.with_structured_output(AssetMappingOutput)
    prompt = _build_llm_prompt(opportunity_data, opportunity_type, normalized_requirements, profile)
    try:
        result: AssetMappingOutput = structured.invoke([
            SystemMessage(content=SYSTEM),
            HumanMessage(content=prompt),
        ])
        # Validate count matches — if mismatch, fall back to heuristic
        if len(result.mappings) != len(normalized_requirements):
            logger.warning(
                "asset_mapping: LLM returned %d mappings but expected %d — falling back to heuristic",
                len(result.mappings),
                len(normalized_requirements),
            )
            return None
        return result.mappings
    except Exception as exc:
        logger.warning("asset_mapping: LLM call failed — %s", exc)
        return None


# ---------------------------------------------------------------------------
# Main node
# ---------------------------------------------------------------------------

def asset_mapping(state: AutoApplyState) -> dict:
    updates = {"current_step": "asset_mapping", "step_history": ["asset_mapping"]}
    if state.get("result", {}).get("status") == "error":
        return updates

    opportunity_type = state.get("opportunity_type", "")
    opportunity_data = state.get("opportunity_data") or {}
    normalized_requirements = state.get("normalized_requirements") or []
    profile = _get_stub_profile()
    uploaded: Dict[str, bool] = {
        k: bool(v) for k, v in (profile.get("uploaded_documents") or {}).items()
    }

    if not normalized_requirements:
        logger.warning("asset_mapping: no normalized_requirements in state — returning empty mapping")
        return {**updates, "asset_mapping": []}

    llm = get_llm()
    mappings: List[AssetMap] | None = None

    if llm is not None:
        mappings = _llm_asset_mapping(
            opportunity_data, opportunity_type, normalized_requirements, profile, llm
        )

    if mappings is None:
        mappings = _heuristic_asset_mapping(normalized_requirements, uploaded)

    logger.info(
        "asset_mapping: produced %d mappings (llm=%s)",
        len(mappings),
        llm is not None and mappings is not None,
    )

    return {**updates, "asset_mapping": [m.model_dump() for m in mappings]}
